/* 句型库数据(v2 对象格式) —— 由迁移脚本一次性从 RAW/EXTRA(v1)转换生成,
 * 之后手动维护,不再依赖 schema-v2.js 的 migrate()/validate()(那两个函数
 * 只是一次性转换/校验工具,不参与运行时打包)。
 * 字段定义见项目根目录 schema-v2.js。
 * id 严格等于数组下标,新增课次数据一律追加在数组末尾,不得调整已有条目顺序,
 * 否则会打乱已保存的学习进度(db.prog 按 id 存储)。
 */
import { PATTERNS_CHUKYU } from "./data/chukyu-01-02.js";
import { PATTERNS_CHUKYU_03 } from "./data/chukyu-03.js";

const SHOKYU = [
  {
    "lesson": 1,
    "level": "初級",
    "pattern": "NはNです",
    "conn": "名詞1 は 名詞2 です",
    "meaning": "…是…(判断句)",
    "exJP": "わたしは会社員です。",
    "exCN": "我是公司职员。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 1,
    "level": "初級",
    "pattern": "NはNではありません",
    "conn": "名詞1 は 名詞2 ではありません",
    "meaning": "…不是…",
    "exJP": "サントスさんは学生ではありません。",
    "exCN": "桑托斯先生不是学生。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 1,
    "level": "初級",
    "pattern": "NはNですか",
    "conn": "句尾 + か",
    "meaning": "…是…吗?(疑问)",
    "exJP": "ミラーさんは会社員ですか。",
    "exCN": "米勒先生是公司职员吗?",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 1,
    "level": "初級",
    "pattern": "Nも",
    "conn": "名詞 + も",
    "meaning": "…也…",
    "exJP": "サントスさんも会社員です。",
    "exCN": "桑托斯先生也是公司职员。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 2,
    "level": "初級",
    "pattern": "これ／それ／あれはNです",
    "conn": "これ・それ・あれ は 名詞です",
    "meaning": "这/那/那(远)是…",
    "exJP": "これは辞書です。",
    "exCN": "这是词典。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 2,
    "level": "初級",
    "pattern": "このN／そのN／あのN",
    "conn": "この・その・あの + 名詞",
    "meaning": "这个/那个…(修饰名词)",
    "exJP": "この傘はわたしのです。",
    "exCN": "这把伞是我的。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 2,
    "level": "初級",
    "pattern": "NのN(所属・内容)",
    "conn": "名詞1 の 名詞2",
    "meaning": "…的…",
    "exJP": "これはコンピューターの本です。",
    "exCN": "这是关于电脑的书。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 3,
    "level": "初級",
    "pattern": "ここ／そこ／あそこはNです",
    "conn": "ここ・そこ・あそこ は 名詞です",
    "meaning": "这里/那里是…",
    "exJP": "ここは食堂です。",
    "exCN": "这里是食堂。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 3,
    "level": "初級",
    "pattern": "NはN(場所)です",
    "conn": "名詞 は 場所 です",
    "meaning": "…在…(位置)",
    "exJP": "電話は2階です。",
    "exCN": "电话在二楼。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 3,
    "level": "初級",
    "pattern": "Nはどこ／いくらですか",
    "conn": "名詞 は どこ・いくら ですか",
    "meaning": "…在哪里/多少钱?",
    "exJP": "このワインはいくらですか。",
    "exCN": "这瓶葡萄酒多少钱?",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 4,
    "level": "初級",
    "pattern": "今〜時〜分です",
    "conn": "今 〜時〜分 です",
    "meaning": "现在是…点…分",
    "exJP": "今4時5分です。",
    "exCN": "现在是4点5分。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 4,
    "level": "初級",
    "pattern": "Vます／Vません／Vました",
    "conn": "動詞ます形",
    "meaning": "动词敬体(现在/否定/过去)",
    "exJP": "毎朝6時に起きます。",
    "exCN": "每天早上6点起床。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 4,
    "level": "初級",
    "pattern": "〜から〜まで",
    "conn": "名詞 から 名詞 まで",
    "meaning": "从…到…",
    "exJP": "9時から5時まで働きます。",
    "exCN": "从9点工作到5点。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 5,
    "level": "初級",
    "pattern": "N(場所)へ行きます",
    "conn": "場所 へ 行きます・来ます・帰ります",
    "meaning": "去/来/回…(移动)",
    "exJP": "来月京都へ行きます。",
    "exCN": "下个月去京都。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 5,
    "level": "初級",
    "pattern": "N(乗り物)で行きます",
    "conn": "乗り物 で 行きます",
    "meaning": "乘…去(交通手段)",
    "exJP": "電車で大阪へ行きます。",
    "exCN": "坐电车去大阪。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 5,
    "level": "初級",
    "pattern": "N(人)と行きます",
    "conn": "人 と 動詞",
    "meaning": "和…一起…",
    "exJP": "家族と日本へ来ました。",
    "exCN": "和家人一起来了日本。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 6,
    "level": "初級",
    "pattern": "NをVます",
    "conn": "名詞 を 動詞(他動詞)",
    "meaning": "…做…(宾语)",
    "exJP": "ジュースを飲みます。",
    "exCN": "喝果汁。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 6,
    "level": "初級",
    "pattern": "N(場所)でVます",
    "conn": "場所 で 動詞",
    "meaning": "在…(地点)做…",
    "exJP": "駅で新聞を買います。",
    "exCN": "在车站买报纸。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 6,
    "level": "初級",
    "pattern": "一緒にVませんか",
    "conn": "動詞ませんか",
    "meaning": "要不要一起…?(邀请)",
    "exJP": "一緒に京都へ行きませんか。",
    "exCN": "要不要一起去京都?",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 6,
    "level": "初級",
    "pattern": "Vましょう",
    "conn": "動詞ましょう",
    "meaning": "…吧(提议)",
    "exJP": "ちょっと休みましょう。",
    "exCN": "休息一下吧。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 7,
    "level": "初級",
    "pattern": "N(道具)でVます",
    "conn": "道具・手段 で 動詞",
    "meaning": "用…(工具)做…",
    "exJP": "はしでご飯を食べます。",
    "exCN": "用筷子吃饭。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 7,
    "level": "初級",
    "pattern": "N(人)にあげます／もらいます",
    "conn": "人 に あげます・もらいます",
    "meaning": "给…/从…得到",
    "exJP": "木村さんに花をあげました。",
    "exCN": "送给了木村小姐花。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 7,
    "level": "初級",
    "pattern": "もうVました",
    "conn": "もう + 動詞ました",
    "meaning": "已经…了",
    "exJP": "もう昼ご飯を食べました。",
    "exCN": "已经吃过午饭了。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 8,
    "level": "初級",
    "pattern": "い形／な形容詞です",
    "conn": "い形容詞です・な形容詞です",
    "meaning": "形容词谓语句",
    "exJP": "富士山は高いです。桜はきれいです。",
    "exCN": "富士山很高。樱花很漂亮。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 8,
    "level": "初級",
    "pattern": "あまり〜ません",
    "conn": "あまり + 否定形",
    "meaning": "不太…",
    "exJP": "この町はあまりにぎやかではありません。",
    "exCN": "这个城市不太热闹。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 8,
    "level": "初級",
    "pattern": "Nはどうですか／どんなNですか",
    "conn": "名詞 は どうですか・どんな 名詞",
    "meaning": "…怎么样?/什么样的…?",
    "exJP": "日本の生活はどうですか。",
    "exCN": "在日本的生活怎么样?",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 9,
    "level": "初級",
    "pattern": "Nが好きです／上手です",
    "conn": "名詞 が 好きです・嫌いです・上手です・下手です",
    "meaning": "喜欢/擅长…",
    "exJP": "わたしはイタリア料理が好きです。",
    "exCN": "我喜欢意大利菜。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 9,
    "level": "初級",
    "pattern": "Nがわかります／あります",
    "conn": "名詞 が わかります・あります",
    "meaning": "懂…/有…",
    "exJP": "わたしは日本語が少しわかります。",
    "exCN": "我懂一点日语。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 9,
    "level": "初級",
    "pattern": "どうして…／〜から",
    "conn": "文 + から",
    "meaning": "为什么…/因为…",
    "exJP": "時間がありませんから、新聞を読みません。",
    "exCN": "因为没有时间,所以不看报纸。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 10,
    "level": "初級",
    "pattern": "Nがあります／います",
    "conn": "名詞 が あります(物)・います(人・動物)",
    "meaning": "有…(存在)",
    "exJP": "机の上に写真があります。",
    "exCN": "桌子上有照片。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 10,
    "level": "初級",
    "pattern": "N(場所)にNがあります／います",
    "conn": "場所 に 名詞 が あります・います",
    "meaning": "在…有…",
    "exJP": "公園に子どもがいます。",
    "exCN": "公园里有孩子。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 10,
    "level": "初級",
    "pattern": "NはN(場所)にあります／います",
    "conn": "名詞 は 場所 に あります・います",
    "meaning": "…在…(所在)",
    "exJP": "東京ディズニーランドは千葉県にあります。",
    "exCN": "东京迪士尼乐园在千叶县。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 11,
    "level": "初級",
    "pattern": "数量詞",
    "conn": "〜つ・〜人・〜枚・〜台・〜本・〜冊 など",
    "meaning": "数量词(个/人/张/台…)",
    "exJP": "りんごを4つ買いました。",
    "exCN": "买了4个苹果。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 11,
    "level": "初級",
    "pattern": "期間に〜回",
    "conn": "期間 に 〜回 動詞",
    "meaning": "(时间段)内…次(频率)",
    "exJP": "1か月に2回映画を見ます。",
    "exCN": "一个月看两次电影。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 11,
    "level": "初級",
    "pattern": "数量詞だけ",
    "conn": "数量詞 + だけ",
    "meaning": "只…(仅仅)",
    "exJP": "りんごを1つだけ買いました。",
    "exCN": "只买了一个苹果。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 12,
    "level": "初級",
    "pattern": "N1はN2より〜",
    "conn": "名詞1 は 名詞2 より 形容詞",
    "meaning": "…比…更…",
    "exJP": "飛行機は船より速いです。",
    "exCN": "飞机比船快。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 12,
    "level": "初級",
    "pattern": "N1とN2とどちらが〜",
    "conn": "名詞1 と 名詞2 と どちらが 〜/〜のほうが〜",
    "meaning": "…和…哪个更…?",
    "exJP": "サッカーと野球とどちらが面白いですか。",
    "exCN": "足球和棒球哪个更有意思?",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 12,
    "level": "初級",
    "pattern": "Nの中で〜が一番〜",
    "conn": "名詞(範囲) の中で 〜が 一番 〜",
    "meaning": "在…之中…最…",
    "exJP": "日本料理の中で寿司が一番好きです。",
    "exCN": "日本菜里面最喜欢寿司。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 12,
    "level": "初級",
    "pattern": "形容詞の過去形",
    "conn": "い形→〜かったです／な形→〜でした",
    "meaning": "形容词过去式",
    "exJP": "昨日は暑かったです。",
    "exCN": "昨天很热。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 13,
    "level": "初級",
    "pattern": "Nがほしいです",
    "conn": "名詞 が ほしいです",
    "meaning": "想要…(东西)",
    "exJP": "わたしは車がほしいです。",
    "exCN": "我想要一辆车。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 13,
    "level": "初級",
    "pattern": "Vたいです",
    "conn": "動詞ます形去ます + たいです",
    "meaning": "想做…",
    "exJP": "沖縄へ行きたいです。",
    "exCN": "想去冲绳。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 13,
    "level": "初級",
    "pattern": "N(場所)へVに行きます",
    "conn": "場所 へ 動詞ます形去ます/名詞 に 行きます",
    "meaning": "去…做…(目的)",
    "exJP": "神戸へ映画を見に行きます。",
    "exCN": "去神户看电影。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 14,
    "level": "初級",
    "pattern": "Vてください",
    "conn": "動詞て形 + ください",
    "meaning": "请做…",
    "exJP": "ちょっと待ってください。",
    "exCN": "请稍等。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 14,
    "level": "初級",
    "pattern": "Vています(進行)",
    "conn": "動詞て形 + います",
    "meaning": "正在做…",
    "exJP": "今雨が降っています。",
    "exCN": "现在正在下雨。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 14,
    "level": "初級",
    "pattern": "Vましょうか",
    "conn": "動詞ましょうか",
    "meaning": "我来…好吗?(主动帮忙)",
    "exJP": "荷物を持ちましょうか。",
    "exCN": "我来帮您拿行李吧?",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 15,
    "level": "初級",
    "pattern": "Vてもいいです",
    "conn": "動詞て形 + もいいです",
    "meaning": "可以做…(许可)",
    "exJP": "ここで写真を撮ってもいいですか。",
    "exCN": "可以在这里拍照吗?",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 15,
    "level": "初級",
    "pattern": "Vてはいけません",
    "conn": "動詞て形 + はいけません",
    "meaning": "不可以做…(禁止)",
    "exJP": "ここでたばこを吸ってはいけません。",
    "exCN": "这里不可以吸烟。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 15,
    "level": "初級",
    "pattern": "Vています(状態・職業)",
    "conn": "動詞て形 + います",
    "meaning": "…着(状态)/从事…",
    "exJP": "わたしは結婚しています。姉は銀行で働いています。",
    "exCN": "我已经结婚了。姐姐在银行工作。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 16,
    "level": "初級",
    "pattern": "Vて、Vて、〜(順序)",
    "conn": "動詞て形 でつなぐ",
    "meaning": "做…,然后做…(先后)",
    "exJP": "朝ジョギングをして、シャワーを浴びて、会社へ行きます。",
    "exCN": "早上跑步,然后洗澡,再去公司。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 16,
    "level": "初級",
    "pattern": "〜くて／〜で(並列)",
    "conn": "い形→くて/な形・名詞→で",
    "meaning": "又…又…(并列描述)",
    "exJP": "ミラーさんは若くて、元気です。",
    "exCN": "米勒先生又年轻又有活力。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 16,
    "level": "初級",
    "pattern": "Vてから",
    "conn": "動詞て形 + から",
    "meaning": "做完…之后再…",
    "exJP": "仕事が終わってから、飲みに行きます。",
    "exCN": "工作结束后去喝酒。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 16,
    "level": "初級",
    "pattern": "N1はN2が〜(属性)",
    "conn": "名詞1 は 名詞2 が 形容詞",
    "meaning": "…的…很…(整体+部分)",
    "exJP": "大阪は食べ物がおいしいです。",
    "exCN": "大阪的食物很好吃。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 17,
    "level": "初級",
    "pattern": "Vないでください",
    "conn": "動詞ない形 + でください",
    "meaning": "请不要做…",
    "exJP": "ここで写真を撮らないでください。",
    "exCN": "请不要在这里拍照。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 17,
    "level": "初級",
    "pattern": "Vなければなりません",
    "conn": "動詞ない形去ない + なければなりません",
    "meaning": "必须做…",
    "exJP": "毎日薬を飲まなければなりません。",
    "exCN": "每天必须吃药。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 17,
    "level": "初級",
    "pattern": "Vなくてもいいです",
    "conn": "動詞ない形去ない + なくてもいいです",
    "meaning": "不做…也可以",
    "exJP": "明日来なくてもいいです。",
    "exCN": "明天不来也可以。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 18,
    "level": "初級",
    "pattern": "Vることができます",
    "conn": "動詞辞書形 + ことができます/名詞 が できます",
    "meaning": "会做…/能做…",
    "exJP": "ミラーさんは漢字を読むことができます。",
    "exCN": "米勒先生会读汉字。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 18,
    "level": "初級",
    "pattern": "趣味はVることです",
    "conn": "趣味は 動詞辞書形 + ことです",
    "meaning": "爱好是做…",
    "exJP": "わたしの趣味は映画を見ることです。",
    "exCN": "我的爱好是看电影。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 18,
    "level": "初級",
    "pattern": "Vる／Nの前に",
    "conn": "動詞辞書形・名詞の + 前に",
    "meaning": "做…之前",
    "exJP": "寝る前に、本を読みます。",
    "exCN": "睡觉前看书。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 19,
    "level": "初級",
    "pattern": "Vたことがあります",
    "conn": "動詞た形 + ことがあります",
    "meaning": "曾经做过…(经历)",
    "exJP": "馬に乗ったことがあります。",
    "exCN": "骑过马。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 19,
    "level": "初級",
    "pattern": "Vたり、Vたりします",
    "conn": "動詞た形 + り、動詞た形 + りします",
    "meaning": "又做…又做…(列举)",
    "exJP": "日曜日はテニスをしたり、映画を見たりします。",
    "exCN": "星期天打打网球、看看电影。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 19,
    "level": "初級",
    "pattern": "〜くなります／〜になります",
    "conn": "い形→く/な形・名詞→に + なります",
    "meaning": "变得…(变化)",
    "exJP": "だんだん寒くなります。",
    "exCN": "渐渐变冷。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 20,
    "level": "初級",
    "pattern": "普通形(简体)",
    "conn": "です・ます → 普通形",
    "meaning": "简体句(朋友间口语)",
    "exJP": "明日東京へ行く。寿司が好きだ。",
    "exCN": "明天去东京。喜欢寿司。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 21,
    "level": "初級",
    "pattern": "〜と思います",
    "conn": "普通形 + と思います",
    "meaning": "我觉得/我认为…",
    "exJP": "明日雨が降ると思います。",
    "exCN": "我觉得明天会下雨。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 21,
    "level": "初級",
    "pattern": "〜と言いました",
    "conn": "「引用」/普通形 + と言いました",
    "meaning": "(某人)说了…",
    "exJP": "首相は来月アメリカへ行くと言いました。",
    "exCN": "首相说下个月去美国。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 21,
    "level": "初級",
    "pattern": "Vるでしょう?",
    "conn": "普通形 + でしょう?(升调)",
    "meaning": "…对吧?(确认)",
    "exJP": "明日パーティーに行くでしょう?",
    "exCN": "明天会去派对的吧?",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 22,
    "level": "初級",
    "pattern": "名詞修飾節",
    "conn": "普通形 + 名詞",
    "meaning": "…的…(定语从句)",
    "exJP": "これはミラーさんが作ったケーキです。",
    "exCN": "这是米勒先生做的蛋糕。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 23,
    "level": "初級",
    "pattern": "〜とき",
    "conn": "普通形・名詞の + とき",
    "meaning": "…的时候",
    "exJP": "図書館で本を借りるとき、カードが要ります。",
    "exCN": "在图书馆借书的时候需要借书卡。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 23,
    "level": "初級",
    "pattern": "Vると、〜",
    "conn": "動詞辞書形 + と",
    "meaning": "一…就…(自然结果)",
    "exJP": "このボタンを押すと、お釣りが出ます。",
    "exCN": "一按这个按钮,零钱就出来。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 24,
    "level": "初級",
    "pattern": "Nをくれます",
    "conn": "人 は わたしに 名詞 を くれます",
    "meaning": "(别人)给我…",
    "exJP": "佐藤さんはわたしにチョコレートをくれました。",
    "exCN": "佐藤小姐给了我巧克力。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 24,
    "level": "初級",
    "pattern": "Vてあげます／もらいます／くれます",
    "conn": "動詞て形 + あげます・もらいます・くれます",
    "meaning": "为别人做/请别人做/别人为我做",
    "exJP": "母はわたしにセーターを送ってくれました。",
    "exCN": "妈妈给我寄来了毛衣。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 25,
    "level": "初級",
    "pattern": "〜たら(条件)",
    "conn": "動詞・形容詞た形 + ら",
    "meaning": "如果…的话/…之后",
    "exJP": "雨が降ったら、出かけません。",
    "exCN": "如果下雨就不出门。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 25,
    "level": "初級",
    "pattern": "〜ても(逆接)",
    "conn": "動詞・形容詞て形 + も",
    "meaning": "即使…也…",
    "exJP": "雨が降っても、出かけます。",
    "exCN": "即使下雨也要出门。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 26,
    "level": "初級",
    "pattern": "〜んです",
    "conn": "普通形 + んです",
    "meaning": "(说明原因/关切询问)",
    "exJP": "どうして遅れたんですか。",
    "exCN": "(你)为什么迟到了呢?",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 26,
    "level": "初級",
    "pattern": "Vていただけませんか",
    "conn": "動詞て形 + いただけませんか",
    "meaning": "能否请您…?(郑重请求)",
    "exJP": "いい先生を紹介していただけませんか。",
    "exCN": "能否请您介绍一位好老师?",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 26,
    "level": "初級",
    "pattern": "疑問詞+Vたらいいですか",
    "conn": "疑問詞 + 動詞た形 + らいいですか",
    "meaning": "该…才好呢?(请教)",
    "exJP": "どこでカメラを買ったらいいですか。",
    "exCN": "在哪里买相机好呢?",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 27,
    "level": "初級",
    "pattern": "可能動詞",
    "conn": "一段:見られる/五段:話せる/する→できる",
    "meaning": "会…/能…(可能形)",
    "exJP": "わたしは日本語が少し話せます。",
    "exCN": "我会说一点日语。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 27,
    "level": "初級",
    "pattern": "見えます／聞こえます",
    "conn": "名詞 が 見えます・聞こえます",
    "meaning": "看得见/听得见(自然感知)",
    "exJP": "新幹線から富士山が見えます。",
    "exCN": "从新干线上看得见富士山。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 27,
    "level": "初級",
    "pattern": "しか〜ません",
    "conn": "名詞 + しか + 否定形",
    "meaning": "只…(带遗憾语气)",
    "exJP": "ローマ字しか書けません。",
    "exCN": "只会写罗马字。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 28,
    "level": "初級",
    "pattern": "Vながら",
    "conn": "動詞ます形去ます + ながら",
    "meaning": "一边…一边…",
    "exJP": "音楽を聞きながら、食事します。",
    "exCN": "一边听音乐一边吃饭。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 28,
    "level": "初級",
    "pattern": "Vています(習慣)",
    "conn": "動詞て形 + います",
    "meaning": "(反复的习惯)",
    "exJP": "毎朝ジョギングをしています。",
    "exCN": "每天早上都跑步。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 28,
    "level": "初級",
    "pattern": "〜し、〜し",
    "conn": "普通形 + し、普通形 + し",
    "meaning": "又…又…(列举理由)",
    "exJP": "田中先生は熱心だし、経験もあります。",
    "exCN": "田中老师既热心,又有经验。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 29,
    "level": "初級",
    "pattern": "Vています(結果の状態)",
    "conn": "動詞て形 + います",
    "meaning": "…着(结果状态)",
    "exJP": "窓が割れています。",
    "exCN": "窗户破了(处于破的状态)。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 29,
    "level": "初級",
    "pattern": "Vてしまいました",
    "conn": "動詞て形 + しまいました",
    "meaning": "(不小心)…了/彻底…了",
    "exJP": "パスポートをなくしてしまいました。",
    "exCN": "不小心把护照弄丢了。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 30,
    "level": "初級",
    "pattern": "Vてあります",
    "conn": "動詞て形 + あります",
    "meaning": "(有人特意)…着(准备好的状态)",
    "exJP": "カレンダーに今月の予定が書いてあります。",
    "exCN": "日历上写着这个月的安排。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 30,
    "level": "初級",
    "pattern": "Vておきます",
    "conn": "動詞て形 + おきます",
    "meaning": "事先做好…(准备)",
    "exJP": "旅行の前に、切符を買っておきます。",
    "exCN": "旅行前先把票买好。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 31,
    "level": "初級",
    "pattern": "意向形(Vよう)",
    "conn": "五段:行こう/一段:食べよう/する→しよう",
    "meaning": "…吧(意志,简体)",
    "exJP": "少し休もう。",
    "exCN": "休息一会儿吧。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 31,
    "level": "初級",
    "pattern": "Vようと思っています",
    "conn": "意向形 + と思っています",
    "meaning": "打算…(内心的打算)",
    "exJP": "週末は海へ行こうと思っています。",
    "exCN": "打算周末去海边。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 31,
    "level": "初級",
    "pattern": "Vるつもりです",
    "conn": "動詞辞書形・ない形 + つもりです",
    "meaning": "打算…/不打算…",
    "exJP": "国へ帰って、会社をつくるつもりです。",
    "exCN": "打算回国开公司。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 31,
    "level": "初級",
    "pattern": "Vる予定です",
    "conn": "動詞辞書形・名詞の + 予定です",
    "meaning": "预定…(计划安排)",
    "exJP": "7月に大阪へ出張する予定です。",
    "exCN": "预定7月去大阪出差。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 32,
    "level": "初級",
    "pattern": "Vたほうがいいです",
    "conn": "動詞た形・ない形 + ほうがいいです",
    "meaning": "最好…/最好不要…(建议)",
    "exJP": "毎日運動したほうがいいです。",
    "exCN": "最好每天运动。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 32,
    "level": "初級",
    "pattern": "〜でしょう(推測)",
    "conn": "普通形 + でしょう",
    "meaning": "大概…吧(推测)",
    "exJP": "明日は晴れるでしょう。",
    "exCN": "明天大概是晴天吧。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 32,
    "level": "初級",
    "pattern": "〜かもしれません",
    "conn": "普通形 + かもしれません",
    "meaning": "也许…(可能性低)",
    "exJP": "約束の時間に間に合わないかもしれません。",
    "exCN": "也许赶不上约定的时间。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 33,
    "level": "初級",
    "pattern": "命令形／禁止形",
    "conn": "五段:行け/一段:食べろ/+ な(禁止)",
    "meaning": "命令/禁止(强硬)",
    "exJP": "逃げろ。ここに入るな。",
    "exCN": "快逃!不许进这里。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 33,
    "level": "初級",
    "pattern": "〜という意味です",
    "conn": "「〜」は 〜という意味です",
    "meaning": "是…的意思",
    "exJP": "「止まれ」は止まらなければならないという意味です。",
    "exCN": "「止まれ」是必须停下的意思。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 33,
    "level": "初級",
    "pattern": "〜と言っていました",
    "conn": "人は 普通形 + と言っていました",
    "meaning": "(某人)说过…(转达)",
    "exJP": "田中さんは明日休むと言っていました。",
    "exCN": "田中先生说他明天休息。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 34,
    "level": "初級",
    "pattern": "Vた／Nのとおりに",
    "conn": "動詞た形・名詞の + とおりに",
    "meaning": "按照…那样做",
    "exJP": "わたしがやったとおりに、やってください。",
    "exCN": "请按照我做的那样做。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 34,
    "level": "初級",
    "pattern": "Vたあとで",
    "conn": "動詞た形・名詞の + あとで",
    "meaning": "…之后",
    "exJP": "仕事が終わったあとで、飲みに行きます。",
    "exCN": "工作结束之后去喝酒。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 34,
    "level": "初級",
    "pattern": "Vて／Vないで(付帯)",
    "conn": "動詞て形/ない形 + で",
    "meaning": "(不)…的状态下做…",
    "exJP": "朝ご飯を食べないで、会社へ来ました。",
    "exCN": "没吃早饭就来公司了。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 35,
    "level": "初級",
    "pattern": "〜ば(条件形)",
    "conn": "五段:押せば/一段:見れば/い形:安ければ",
    "meaning": "如果…就…(假定条件)",
    "exJP": "このボタンを押せば、窓が開きます。",
    "exCN": "按这个按钮的话,窗户就会开。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 35,
    "level": "初級",
    "pattern": "〜なら",
    "conn": "名詞・普通形 + なら",
    "meaning": "要说…的话(就对方话题建议)",
    "exJP": "温泉なら、白馬がいいですよ。",
    "exCN": "要说温泉的话,白马不错哦。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 36,
    "level": "初級",
    "pattern": "〜ように(目的)",
    "conn": "動詞辞書形・ない形 + ように",
    "meaning": "为了能…(目的)",
    "exJP": "早く泳げるように、毎日練習しています。",
    "exCN": "为了能早点学会游泳,每天都在练习。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 36,
    "level": "初級",
    "pattern": "Vようになりました",
    "conn": "動詞辞書形(可能形) + ようになりました",
    "meaning": "变得能…了(能力变化)",
    "exJP": "日本語が話せるようになりました。",
    "exCN": "变得会说日语了。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 36,
    "level": "初級",
    "pattern": "Vようにしています",
    "conn": "動詞辞書形・ない形 + ようにしています",
    "meaning": "坚持做…(努力保持)",
    "exJP": "毎日日記を書くようにしています。",
    "exCN": "坚持每天写日记。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 37,
    "level": "初級",
    "pattern": "受身(被动)",
    "conn": "五段:言われる/一段:見られる/する→される",
    "meaning": "被…(被动)",
    "exJP": "わたしは部長に褒められました。",
    "exCN": "我被部长表扬了。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 38,
    "level": "初級",
    "pattern": "Vるのは〜です",
    "conn": "動詞辞書形 + のは 形容詞です",
    "meaning": "做…(这件事)很…",
    "exJP": "絵をかくのは楽しいです。",
    "exCN": "画画很开心。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 38,
    "level": "初級",
    "pattern": "Vるのが〜です",
    "conn": "動詞辞書形 + のが 好き・上手 など",
    "meaning": "喜欢/擅长做…",
    "exJP": "わたしは花を育てるのが好きです。",
    "exCN": "我喜欢养花。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 38,
    "level": "初級",
    "pattern": "Vるのを忘れました",
    "conn": "動詞辞書形 + のを忘れました",
    "meaning": "忘了做…",
    "exJP": "車の窓を閉めるのを忘れました。",
    "exCN": "忘了关车窗。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 38,
    "level": "初級",
    "pattern": "〜のは〜です(強調)",
    "conn": "強調したい部分を後ろに",
    "meaning": "…的是…(强调句)",
    "exJP": "初めて日本へ来たのは10年前です。",
    "exCN": "第一次来日本是10年前。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 39,
    "level": "初級",
    "pattern": "〜て／〜くて(原因)",
    "conn": "動詞て形・い形くて・な形で",
    "meaning": "因为…(自然感情/状态的原因)",
    "exJP": "ニュースを聞いて、びっくりしました。",
    "exCN": "听到新闻吓了一跳。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 39,
    "level": "初級",
    "pattern": "〜ので",
    "conn": "普通形(な形・名詞は+な) + ので",
    "meaning": "因为…(委婉客观理由)",
    "exJP": "用事があるので、お先に失礼します。",
    "exCN": "因为有事,先告辞了。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 40,
    "level": "初級",
    "pattern": "疑問詞〜か",
    "conn": "疑問詞 + 普通形 + か",
    "meaning": "…呢(嵌入疑问)",
    "exJP": "パーティーに何人来るか、わかりません。",
    "exCN": "不知道有多少人来参加派对。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 40,
    "level": "初級",
    "pattern": "〜かどうか",
    "conn": "普通形 + かどうか",
    "meaning": "是否…",
    "exJP": "忘れ物がないかどうか、調べてください。",
    "exCN": "请检查一下有没有遗忘的东西。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 40,
    "level": "初級",
    "pattern": "Vてみます",
    "conn": "動詞て形 + みます",
    "meaning": "试着做…",
    "exJP": "もう一度考えてみます。",
    "exCN": "再考虑考虑看。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 41,
    "level": "初級",
    "pattern": "いただきます／くださいます",
    "conn": "目上の人から:いただく・くださる",
    "meaning": "(敬语)得到/给我",
    "exJP": "わたしは部長にワインをいただきました。",
    "exCN": "我从部长那里得到了葡萄酒。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 41,
    "level": "初級",
    "pattern": "Vていただきました／てくださいました",
    "conn": "動詞て形 + いただきます・くださいます",
    "meaning": "(敬语)请人做/别人为我做",
    "exJP": "部長の奥さんに茶道を教えていただきました。",
    "exCN": "请部长夫人教了我茶道。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 42,
    "level": "初級",
    "pattern": "〜ために(目的)",
    "conn": "動詞辞書形・名詞の + ために",
    "meaning": "为了…(意志性目的)",
    "exJP": "家を買うために、貯金しています。",
    "exCN": "为了买房子在存钱。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 42,
    "level": "初級",
    "pattern": "〜のに(用途)",
    "conn": "動詞辞書形 + のに 使います・要ります など",
    "meaning": "用于…(用途/评价)",
    "exJP": "このはさみは花を切るのに使います。",
    "exCN": "这把剪刀用来剪花。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 43,
    "level": "初級",
    "pattern": "〜そうです(様態)",
    "conn": "動詞ます形去ます・形容詞語幹 + そうです",
    "meaning": "眼看要…/看起来…",
    "exJP": "今にも雨が降りそうです。このケーキはおいしそうです。",
    "exCN": "眼看就要下雨了。这个蛋糕看起来很好吃。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 43,
    "level": "初級",
    "pattern": "Vてきます",
    "conn": "動詞て形 + きます",
    "meaning": "去…(马上)回来",
    "exJP": "ちょっとジュースを買ってきます。",
    "exCN": "我去买瓶果汁就回来。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 44,
    "level": "初級",
    "pattern": "〜すぎます",
    "conn": "動詞ます形去ます・形容詞語幹 + すぎます",
    "meaning": "过于…/…过头",
    "exJP": "ゆうべ飲みすぎました。",
    "exCN": "昨晚喝多了。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 44,
    "level": "初級",
    "pattern": "Vやすい／Vにくい",
    "conn": "動詞ます形去ます + やすい・にくい",
    "meaning": "容易…/难以…",
    "exJP": "このパソコンは使いやすいです。",
    "exCN": "这台电脑很好用。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 44,
    "level": "初級",
    "pattern": "〜く／〜にします",
    "conn": "い形→く/な形・名詞→に + します",
    "meaning": "把…弄成…(人为改变)",
    "exJP": "音を小さくしてください。",
    "exCN": "请把声音调小。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 45,
    "level": "初級",
    "pattern": "〜場合は",
    "conn": "動詞・形容詞普通形・名詞の + 場合は",
    "meaning": "…的情况下(万一)",
    "exJP": "領収書をなくした場合は、どうしたらいいですか。",
    "exCN": "万一弄丢了发票,该怎么办?",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 45,
    "level": "初級",
    "pattern": "〜のに(逆接)",
    "conn": "普通形(な形・名詞+な) + のに",
    "meaning": "明明…却…(意外/不满)",
    "exJP": "約束をしたのに、彼女は来ませんでした。",
    "exCN": "明明约好了,她却没来。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 46,
    "level": "初級",
    "pattern": "〜ところです",
    "conn": "辞書形+ところ/ている+ところ/た形+ところ",
    "meaning": "正要…/正在…/刚刚…",
    "exJP": "これから昼ご飯を食べるところです。",
    "exCN": "现在正要吃午饭。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 46,
    "level": "初級",
    "pattern": "Vたばかりです",
    "conn": "動詞た形 + ばかりです",
    "meaning": "刚…(说话人觉得时间短)",
    "exJP": "さっき駅に着いたばかりです。",
    "exCN": "刚刚到车站。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 46,
    "level": "初級",
    "pattern": "〜はずです",
    "conn": "普通形(な形な・名詞の) + はずです",
    "meaning": "按理说应该…(有依据推断)",
    "exJP": "ミラーさんは今日来るはずです。",
    "exCN": "米勒先生今天应该会来。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 47,
    "level": "初級",
    "pattern": "〜そうです(伝聞)",
    "conn": "普通形 + そうです",
    "meaning": "听说…(传闻)",
    "exJP": "天気予報によると、明日は寒くなるそうです。",
    "exCN": "据天气预报说,明天会变冷。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 47,
    "level": "初級",
    "pattern": "〜ようです",
    "conn": "普通形(な形な・名詞の) + ようです",
    "meaning": "好像…(根据观察推测)",
    "exJP": "人がおおぜい集まっていますね。事故のようです。",
    "exCN": "聚集了好多人啊,好像是出事故了。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 48,
    "level": "初級",
    "pattern": "使役(させます)",
    "conn": "五段:行かせる/一段:食べさせる/する→させる",
    "meaning": "让/叫(某人)做…",
    "exJP": "娘にピアノを習わせます。",
    "exCN": "让女儿学钢琴。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 48,
    "level": "初級",
    "pattern": "使役て形+いただけませんか",
    "conn": "使役て形 + いただけませんか",
    "meaning": "能否允许我…?(请求许可)",
    "exJP": "すみませんが、早く帰らせていただけませんか。",
    "exCN": "不好意思,能让我早点回去吗?",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 49,
    "level": "初級",
    "pattern": "尊敬語",
    "conn": "れます・られます/お〜になります/特殊形",
    "meaning": "尊敬语(抬高对方)",
    "exJP": "社長はもう帰られました。先生は何時にお出かけになりますか。",
    "exCN": "社长已经回去了。老师几点出门?",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 49,
    "level": "初級",
    "pattern": "お〜ください",
    "conn": "お + 動詞ます形去ます + ください",
    "meaning": "请您…(郑重指示)",
    "exJP": "こちらで少々お待ちください。",
    "exCN": "请您在这边稍等。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 50,
    "level": "初級",
    "pattern": "謙譲語",
    "conn": "お〜します・いたします/特殊形(伺う・申す など)",
    "meaning": "谦让语(降低自己)",
    "exJP": "重そうですね。お持ちしましょう。明日3時に伺います。",
    "exCN": "看起来很重,我来帮您拿吧。明天3点拜访您。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": false
  },
  {
    "lesson": 3,
    "level": "初級",
    "pattern": "Nをください",
    "conn": "名詞 を ください",
    "meaning": "请给我…(购物·点单)",
    "exJP": "すみません、このりんごを3つください。",
    "exCN": "不好意思,请给我3个这种苹果。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": true
  },
  {
    "lesson": 4,
    "level": "初級",
    "pattern": "〜曜日",
    "conn": "日・月・火・水・木・金・土曜日",
    "meaning": "星期…",
    "exJP": "今日は何曜日ですか。…水曜日です。",
    "exCN": "今天星期几?…星期三。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": true
  },
  {
    "lesson": 5,
    "level": "初級",
    "pattern": "いつ〜ますか",
    "conn": "いつ + 動詞",
    "meaning": "什么时候…?",
    "exJP": "いつ日本へ来ましたか。",
    "exCN": "你是什么时候来日本的?",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": true
  },
  {
    "lesson": 5,
    "level": "初級",
    "pattern": "どこ[へ]も〜ません",
    "conn": "疑問詞 + も + 否定形",
    "meaning": "哪儿也不…/谁也不…",
    "exJP": "日曜日はどこへも行きません。",
    "exCN": "星期天哪儿也不去。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": true
  },
  {
    "lesson": 6,
    "level": "初級",
    "pattern": "Nをお願いします",
    "conn": "名詞 を お願いします",
    "meaning": "麻烦给我…(比ください更礼貌)",
    "exJP": "コーヒーをお願いします。",
    "exCN": "麻烦来一杯咖啡。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": true
  },
  {
    "lesson": 8,
    "level": "初級",
    "pattern": "〜が、〜(前置き)",
    "conn": "文 + が、文",
    "meaning": "…,(不过/请问)…(委婉开场)",
    "exJP": "すみませんが、駅はどこですか。",
    "exCN": "不好意思,请问车站在哪里?",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": true
  },
  {
    "lesson": 8,
    "level": "初級",
    "pattern": "〜ね／〜よ(終助詞)",
    "conn": "文末 + ね・よ",
    "meaning": "…呢(共鸣)/…哦(告知)",
    "exJP": "今日は暑いですね。この店、おいしいですよ。",
    "exCN": "今天真热啊。这家店很好吃哦。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": true
  },
  {
    "lesson": 9,
    "level": "初級",
    "pattern": "よく／あまり／全然",
    "conn": "頻度副詞 + 動詞(全然・あまりは否定)",
    "meaning": "经常/不太/完全不…",
    "exJP": "彼は全然お酒を飲みません。",
    "exCN": "他完全不喝酒。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": true
  },
  {
    "lesson": 10,
    "level": "初級",
    "pattern": "Nの上／下／中／隣",
    "conn": "名詞 の 上・下・中・前・後ろ・隣・近く",
    "meaning": "…的上面/里面/旁边(方位)",
    "exJP": "銀行は郵便局の隣にあります。",
    "exCN": "银行在邮局旁边。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": true
  },
  {
    "lesson": 10,
    "level": "初級",
    "pattern": "〜や〜(など)",
    "conn": "名詞 や 名詞(など)",
    "meaning": "…和…等(不完全列举)",
    "exJP": "机の上に本やペンなどがあります。",
    "exCN": "桌上有书和笔等东西。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": true
  },
  {
    "lesson": 11,
    "level": "初級",
    "pattern": "どのくらい",
    "conn": "どのくらい かかりますか など",
    "meaning": "多长时间/多少(询问程度)",
    "exJP": "家から会社までどのくらいかかりますか。",
    "exCN": "从家到公司要花多长时间?",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": true
  },
  {
    "lesson": 11,
    "level": "初級",
    "pattern": "〜ずつ",
    "conn": "数量詞 + ずつ",
    "meaning": "每…各…",
    "exJP": "一人に2枚ずつ配ってください。",
    "exCN": "请给每人各发两张。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": true
  },
  {
    "lesson": 12,
    "level": "初級",
    "pattern": "〜と同じ／〜と違います",
    "conn": "名詞 と 同じです・違います",
    "meaning": "和…一样/不一样",
    "exJP": "わたしのかばんはあなたのと同じです。",
    "exCN": "我的包和你的一样。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": true
  },
  {
    "lesson": 13,
    "level": "初級",
    "pattern": "何か／どこか",
    "conn": "何か・どこか + 動詞",
    "meaning": "(吃)点什么/(去)个什么地方",
    "exJP": "おなかがすきましたね。何か食べたいです。",
    "exCN": "肚子饿了呢,想吃点什么。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": true
  },
  {
    "lesson": 13,
    "level": "初級",
    "pattern": "Vたがっています",
    "conn": "動詞ます形去ます + たがっています",
    "meaning": "(第三人称)想…",
    "exJP": "娘は犬を飼いたがっています。",
    "exCN": "女儿很想养狗。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": true
  },
  {
    "lesson": 14,
    "level": "初級",
    "pattern": "V方(かた)",
    "conn": "動詞ます形去ます + 方",
    "meaning": "…的方法(读法/用法/做法)",
    "exJP": "この漢字の読み方を教えてください。",
    "exCN": "请告诉我这个汉字的读法。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": true
  },
  {
    "lesson": 15,
    "level": "初級",
    "pattern": "まだVていません",
    "conn": "まだ + 動詞て形 + いません",
    "meaning": "还没…(与もう〜ました相对)",
    "exJP": "昼ご飯はまだ食べていません。",
    "exCN": "午饭还没吃。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": true
  },
  {
    "lesson": 16,
    "level": "初級",
    "pattern": "どうやって",
    "conn": "どうやって + 動詞",
    "meaning": "怎么(做)?(询问方式)",
    "exJP": "駅までどうやって行きますか。",
    "exCN": "到车站怎么走?",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": true
  },
  {
    "lesson": 17,
    "level": "初級",
    "pattern": "〜なくちゃ／〜なきゃ(口語)",
    "conn": "〜なければならない の口語縮約形",
    "meaning": "得…了(口语)",
    "exJP": "もう遅いから、帰らなくちゃ。",
    "exCN": "已经很晚了,我得回去了。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": true
  },
  {
    "lesson": 18,
    "level": "初級",
    "pattern": "Vることがあります",
    "conn": "動詞辞書形・ない形 + ことがあります",
    "meaning": "有时会…",
    "exJP": "忙しいとき、昼ご飯を食べないことがあります。",
    "exCN": "忙的时候有时不吃午饭。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": true
  },
  {
    "lesson": 20,
    "level": "初級",
    "pattern": "〜かな(口語)",
    "conn": "普通形 + かな",
    "meaning": "…吗/…呢(自言自语的疑问)",
    "exJP": "明日は晴れるかな。",
    "exCN": "明天会放晴吗(嘀咕)。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": true
  },
  {
    "lesson": 21,
    "level": "初級",
    "pattern": "〜でしょうか",
    "conn": "文 + でしょうか",
    "meaning": "…吗?(比ですか更委婉)",
    "exJP": "田中さんは今日来るでしょうか。",
    "exCN": "田中先生今天会来吗?",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": true
  },
  {
    "lesson": 22,
    "level": "初級",
    "pattern": "〜というN",
    "conn": "名詞 + という + 名詞",
    "meaning": "叫做…的…",
    "exJP": "「さくら」というレストランを知っていますか。",
    "exCN": "你知道一家叫「さくら」的餐厅吗?",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": true
  },
  {
    "lesson": 24,
    "level": "初級",
    "pattern": "〜てくれてありがとう",
    "conn": "動詞て形 + くれて、ありがとう",
    "meaning": "谢谢你为我…",
    "exJP": "手伝ってくれて、ありがとう。",
    "exCN": "谢谢你帮我。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": true
  },
  {
    "lesson": 25,
    "level": "初級",
    "pattern": "もし〜たら",
    "conn": "もし + 〜たら",
    "meaning": "如果…(强调假设)",
    "exJP": "もし1億円あったら、何をしたいですか。",
    "exCN": "如果有一亿日元,你想做什么?",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": true
  },
  {
    "lesson": 25,
    "level": "初級",
    "pattern": "〜たら(発見)",
    "conn": "〜たら、〜た(過去)",
    "meaning": "一…发现…(意外发现)",
    "exJP": "家に帰ったら、友達が来ていました。",
    "exCN": "一回到家,发现朋友来了。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": true
  },
  {
    "lesson": 26,
    "level": "初級",
    "pattern": "〜んですが、〜",
    "conn": "〜んですが + 依頼・相談",
    "meaning": "我…,(能不能…)(委婉引出请求)",
    "exJP": "パソコンが動かないんですが、ちょっと見ていただけませんか。",
    "exCN": "我电脑动不了了,能帮我看一下吗?",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": true
  },
  {
    "lesson": 26,
    "level": "初級",
    "pattern": "〜たらどうですか",
    "conn": "動詞た形 + らどうですか",
    "meaning": "…怎么样?(提建议)",
    "exJP": "薬を飲んだらどうですか。",
    "exCN": "吃点药怎么样?",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": true
  },
  {
    "lesson": 27,
    "level": "初級",
    "pattern": "疑問詞+でも",
    "conn": "何でも・いつでも・どこでも・だれでも",
    "meaning": "无论什么/随时/哪里都…",
    "exJP": "わからないことがあったら、何でも聞いてください。",
    "exCN": "有不懂的,什么都可以问。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": true
  },
  {
    "lesson": 28,
    "level": "初級",
    "pattern": "〜とか、〜とか",
    "conn": "名詞・動詞 + とか",
    "meaning": "…啦…啦(口语列举)",
    "exJP": "日曜日は掃除とか洗濯とかをします。",
    "exCN": "星期天做做扫除啦、洗衣服啦。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": true
  },
  {
    "lesson": 29,
    "level": "初級",
    "pattern": "〜ちゃった(口語)",
    "conn": "〜てしまった の口語縮約形",
    "meaning": "(口语)不小心…了",
    "exJP": "電車の中にかさを忘れちゃった。",
    "exCN": "把伞忘在电车里了。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": true
  },
  {
    "lesson": 30,
    "level": "初級",
    "pattern": "〜まま",
    "conn": "動詞た形・名詞の + まま",
    "meaning": "保持…的状态(没变)",
    "exJP": "電気をつけたまま、出かけてしまいました。",
    "exCN": "开着灯就出门了。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": true
  },
  {
    "lesson": 31,
    "level": "初級",
    "pattern": "Vることにしました",
    "conn": "動詞辞書形・ない形 + ことにしました",
    "meaning": "决定…(自己做的决定)",
    "exJP": "来年、日本へ留学することにしました。",
    "exCN": "我决定明年去日本留学。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": true
  },
  {
    "lesson": 31,
    "level": "初級",
    "pattern": "Vることになりました",
    "conn": "動詞辞書形・ない形 + ことになりました",
    "meaning": "(客观)定下来要…",
    "exJP": "来月、大阪へ転勤することになりました。",
    "exCN": "(公司安排)下个月要调去大阪了。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": true
  },
  {
    "lesson": 32,
    "level": "初級",
    "pattern": "きっと／たぶん／もしかしたら",
    "conn": "副詞 +(でしょう・かもしれません)",
    "meaning": "一定/大概/说不定(推测副词呼应)",
    "exJP": "明日はたぶん雨が降るでしょう。",
    "exCN": "明天大概会下雨吧。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": true
  },
  {
    "lesson": 33,
    "level": "初級",
    "pattern": "Vなさい",
    "conn": "動詞ます形去ます + なさい",
    "meaning": "(父母对孩子等)快…!",
    "exJP": "早く宿題をしなさい。",
    "exCN": "快点写作业!",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": true
  },
  {
    "lesson": 35,
    "level": "初級",
    "pattern": "〜ばよかった",
    "conn": "動詞ば形 + よかった",
    "meaning": "要是…就好了(后悔)",
    "exJP": "かさを持ってくればよかった。",
    "exCN": "要是带伞来就好了。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": true
  },
  {
    "lesson": 37,
    "level": "初級",
    "pattern": "迷惑の受身",
    "conn": "わたしは 人に 〜られました",
    "meaning": "被…(受害·添麻烦的被动)",
    "exJP": "電車で隣の人に足を踏まれました。",
    "exCN": "在电车上被旁边的人踩了脚。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": true
  },
  {
    "lesson": 39,
    "level": "初級",
    "pattern": "〜て、すみません",
    "conn": "動詞て形 + すみません",
    "meaning": "因为…,对不起",
    "exJP": "返事が遅れて、すみません。",
    "exCN": "回复晚了,对不起。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": true
  },
  {
    "lesson": 40,
    "level": "初級",
    "pattern": "Vてみたいです",
    "conn": "動詞て形 + みたいです",
    "meaning": "想尝试一次…",
    "exJP": "一度着物を着てみたいです。",
    "exCN": "想穿一次和服试试。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": true
  },
  {
    "lesson": 43,
    "level": "初級",
    "pattern": "Vていきます",
    "conn": "動詞て形 + いきます",
    "meaning": "…了再去/…着去(与てきます相对)",
    "exJP": "寒いですから、コートを着ていきます。",
    "exCN": "很冷,所以穿上大衣去。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": true
  },
  {
    "lesson": 44,
    "level": "初級",
    "pattern": "Nにします(選択)",
    "conn": "名詞 + にします",
    "meaning": "决定要…(点单·选择)",
    "exJP": "飲み物は何にしますか。…コーヒーにします。",
    "exCN": "饮料要什么?…我要咖啡。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": true
  },
  {
    "lesson": 45,
    "level": "初級",
    "pattern": "いくら〜ても",
    "conn": "いくら + 〜ても",
    "meaning": "无论怎么…都…",
    "exJP": "いくら押しても、ドアが開きません。",
    "exCN": "怎么推门都打不开。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": true
  },
  {
    "lesson": 46,
    "level": "初級",
    "pattern": "〜はずがありません",
    "conn": "普通形 + はずがありません",
    "meaning": "不可能…(有依据的否定)",
    "exJP": "まじめな彼が嘘をつくはずがありません。",
    "exCN": "认真的他不可能说谎。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": true
  },
  {
    "lesson": 47,
    "level": "初級",
    "pattern": "〜らしいです",
    "conn": "普通形 + らしいです",
    "meaning": "好像/据说…(听来的推断)",
    "exJP": "あの二人は来月結婚するらしいです。",
    "exCN": "那两个人好像下个月要结婚。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": true
  },
  {
    "lesson": 48,
    "level": "初級",
    "pattern": "使役受身(させられる)",
    "conn": "五段:飲まされる/一段:食べさせられる",
    "meaning": "被迫做…",
    "exJP": "子どものとき、母に嫌いな野菜を食べさせられました。",
    "exCN": "小时候被妈妈逼着吃讨厌的蔬菜。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": true
  },
  {
    "lesson": 49,
    "level": "初級",
    "pattern": "お／ご+N(美化語)",
    "conn": "お + 和語/ご + 漢語",
    "meaning": "(礼貌接头词)您的…",
    "exJP": "お名前とご住所をお書きください。",
    "exCN": "请写下您的姓名和住址。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": true
  },
  {
    "lesson": 50,
    "level": "初級",
    "pattern": "〜ております(謙譲)",
    "conn": "動詞て形 + おります",
    "meaning": "(谦让)正在…(商务·电话用语)",
    "exJP": "田中はただ今、席を外しております。",
    "exCN": "田中现在不在座位上。",
    "extras": [],
    "contrasts": [],
    "explain": "",
    "ext": true
  }
];

export const PATTERNS = [
  ...SHOKYU,
  ...PATTERNS_CHUKYU.map((p) => ({ ...p, ext: false })),
  ...PATTERNS_CHUKYU_03.map((p) => ({ ...p, ext: false })),
].map((p, i) => ({ ...p, id: i }));

/* 学习与展示顺序:按课次排序;id 保持稳定,已保存的进度不受影响 */
export const ORDERED = [...PATTERNS].sort((a, b) => a.lesson - b.lesson || a.id - b.id);
